class SongModel {
  final String? idSong, singer, title, songUrl, image, lyric;
  final List<String>? likes;

  SongModel({
    this.idSong,
    this.image,
    this.likes,
    this.lyric,
    this.singer,
    this.songUrl,
    this.title,
  });
}

List<SongModel> listSongs = [
  SongModel(
      idSong: 'id_song1',
      singer: 'Adele',
      title: 'Easy On Me',
      songUrl: 'Adele-EasyOnMe(OfficialLyricVideo).mp3',
      image: 'Adele - Easy On Me (Official Lyric Video).jpg',
      lyric: 'Adele - Easy On Me (Official Lyric Video).lrc',
      likes: [
        'user1',
        'user2',
        'user3',
        'user4',
        'user5',
        'user6',
        'user7',
      ]),
  SongModel(
    idSong: 'id_song2',
    title: 'Sang Dewi',
    singer: 'Lyodra, Andi Rianto',
    songUrl: 'Lyodra,AndiRianto-SangDewi(OfficialLyricVideo).mp3',
    image: 'Lyodra, Andi Rianto - Sang Dewi (Official Lyric Video).jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user7',
    ],
  ),
  SongModel(
    idSong: 'id_song3',
    title: 'Lebih Dari Egoku',
    singer: 'Mawar de Jongh',
    songUrl: 'MawardeJongh-LebihDariEgoku-OfficialMusicVideo.mp3',
    image: 'Mawar de Jongh - Lebih Dari Egoku - Official Music Video.jpg',
    lyric: 'Mawar de Jongh - Lebih Dari Egoku - Official Music Video.lrc',
    likes: [
      'user2',
      'user3',
      'user4',
    ],
  ),
  SongModel(
    idSong: 'id_song4',
    title: 'Bertaut',
    singer: 'Nadin Amizah',
    songUrl: 'NadinAmizah-Bertaut(OfficialMusicVideo).mp3',
    image: 'Nadin Amizah - Bertaut (Official Music Video).jpg',
    lyric: 'Nadin Amizah - Bertaut (Official Music Video).lrc',
    likes: [
      'user2',
      'user3',
    ],
  ),
  SongModel(
    idSong: 'id_song5',
    title: 'Lathi',
    singer: 'Weird Genius ft. Sara Fajira',
    songUrl: 'WeirdGenius-Lathi(ft.SaraFajira)OfficialMusicVideo.mp3',
    image: 'Weird Genius - Lathi (ft. Sara Fajira) Official Music Video.jpg',
    lyric: 'Weird Genius - Lathi (ft. Sara Fajira) Official Music Video.lrc',
    likes: [
      'user2',
      'user3',
      'user5',
    ],
  ),
  SongModel(
    idSong: 'id_song6',
    title: 'Cukup Tau',
    singer: 'Rizky Febian',
    songUrl: 'RizkyFebian-CukupTau(OfficialMusicVideo).mp3',
    image: 'Rizky Febian - Cukup Tau (Official Music Video).png',
    lyric: 'Rizky Febian - Cukup Tau (Official Music Video).lrc',
    likes: [
      'user2',
      'user3',
      'user4',
    ],
  ),
  SongModel(
    idSong: 'id_song7',
    title: 'Tak Ingin Usai',
    singer: 'Keisya Levronka',
    songUrl: 'KeisyaLevronka-TakInginUsaiOfficialLyricVideo.mp3',
    image: 'Keisya Levronka - Tak Ingin Usai Official Lyric Video.png',
    lyric: 'Keisya Levronka - Tak Ingin Usai Official Lyric Video.lrc',
    likes: [
      'user2',
      'user3',
      'user6',
    ],
  ),
  SongModel(
    idSong: 'id_song8',
    title: 'Call me',
    singer: 'Wren Evans',
    songUrl:
        'yt1s.com - WREN EVANS  Call Me  LOI CHOI The First Album ft itsnk.mp3',
    image: 'Call me.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song9',
    title: 'Waiting for you',
    singer: 'Mono',
    songUrl: 'MONO - Waiting For You (Album 22 - Track No.10).mp3',
    image: 'waiting for you.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user19',
      'user9',
      'user14',
      'user17',
      'user1',
      'user15',
      'user16',
    ],
  ),
  SongModel(
    idSong: 'id_song10',
    title: 'Muộn rồi mà sao còn',
    singer: 'Sơn tùng MTP',
    songUrl: 'tp-muon-roi-ma-sao-con-official-music-video.mp3',
    image: 'muộn rồi mà sao còn.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song11',
    title: 'Anh đã sai',
    singer: 'Only C',
    songUrl: 'yt1s.com - Anh Đã Sai  OnlyC Official MV.mp3',
    image: 'Anh đã sai.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song12',
    title: 'Bật tình yêu lên',
    singer: 'Hòa Minzy - Tăng Duy Tân',
    songUrl:
        'yt1s.com - Bật Tình Yêu Lên  Hòa Minzy x Tăng Duy Tân  MV Lyrics.mp3',
    image: 'Bật tình yêu lên.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song13',
    title: 'Anh tự do nhưng cô đơn',
    singer: 'Đạt G',
    songUrl:
        'yt1s.com - Đạt G  Anh Tự Do Nhưng Cô Đơn  Live at DearOcean DatGMusic.mp3',
    image: 'Anh tự do nhưng cô đơn.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song14',
    title: 'Sau tất cả',
    singer: 'Erik',
    songUrl: 'yt1s.com - ERIK  SAU TẤT CẢ  Official Music Video.mp3',
    image: 'Sau tất cả.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song15',
    title: 'Nhạtfine',
    singer: 'GREY D - 52Hz',
    songUrl: 'yt1s.com - GREY D x 52Hz  nhạtfine  performance video.mp3',
    image: 'nhạtfine.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song16',
    title: 'See tình',
    singer: 'Hoàng Thùy Linh',
    songUrl: 'yt1s.com - Hoàng Thuỳ Linh  See Tình  Official Music Video.mp3',
    image: 'See tình.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song17',
    title: 'Có em',
    singer: 'Madihu - LowG',
    songUrl: 'yt1s.com - Madihu  Có em Feat Low G Official MV.mp3',
    image: 'Có em.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song18',
    title: 'Người ấy',
    singer: 'Trịnh Thăng Bình',
    songUrl: 'yt1s.com - NGƯỜI ẤY  TRỊNH THĂNG BÌNH  HEADPHONE SHOW.mp3',
    image: 'Người ấy.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song19',
    title: 'Còn gì đau hơn chữ đã từng',
    singer: 'Quân AP',
    songUrl: 'yt1s.com - QUÂN AP  Còn Gì Đau Hơn Chữ Đã Từng  Lyrics Audio.mp3',
    image: 'Congidauhonchudatung.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song20',
    title: 'Sớm mai',
    singer: 'Pialinh - Ronboogz',
    songUrl:
        'yt1s.com - Sớm Mai  PiaLinh Ronboogz BONNEX Official Music Video.mp3',
    image: 'Pialinh.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song21',
    title: 'Yêu anh đi mẹ anh bán bánh mì',
    singer: 'Phúc Du',
    songUrl:
        'yt1s.com - PHÚC DU  yêu anh đi mẹ anh bán bánh mì MV OFFICIAL.mp3',
    image: 'PhucDu.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
  SongModel(
    idSong: 'id_song22',
    title: 'Không thích',
    singer: 'LowG',
    songUrl: 'yt1s.com - Không Thích  Low G  Rap Nhà Làm.mp3',
    image: 'LowG.jpg',
    lyric: '',
    likes: [
      'user2',
      'user3',
      'user4',
      'user6',
      'user20',
      'user9',
      'user13',
      'user17',
      'user1',
      'user15',
    ],
  ),
];
